server:
  port: 8000
  servlet:
    context-path: /security/v1

spring:
  redis:
    host: localhost
    port: 6379
    password: qwe123

keycloak:
  realm: Demo-Realm
  auth-server-url: http://localhost:8080/auth
  ssl-required: external
  resource: springboot-microservice
  credentials:
    secret: 88e12db1-94cb-4190-b1cd-ff3f1047310b
  use-resource-role-mappings: true
  bearer-only: true